### PR TITLE
Upgrade SDL2 to 2.0.20

### LINKED ISSUE #60: add SDL_GetTicks64()
pretty ez thanks m9

https://wiki.libsdl.org/SDL_GetTicks64

### PR DESCRIPTION
**Pull request by Gnimuc**
fix #60

### CODE REVIEW

**Review by mfiano — COMMENTED** [review]
Can I ask what the technical reasons are, if any, that we are only updating to a pretty ancient version? ...and one that does not even support subpixel rects yet or a lot of bug fixes that have made it into later releases.

**Comment by Gnimuc** [comment]
The latest version on [Ygg](https://github.com/JuliaPackaging/Yggdrasil/blob/a3d6fcc35cce625b8cba39d5ca7ce3b7f3ae0eac/S/SDL2/build_tarballs.jl#L6) is 2.0.20. 

Someone needs to invest time to upgrade [those SDL JLL packages](https://github.com/JuliaPackaging/Yggdrasil/tree/master/S) and that's not as trivial as updating the version number, see https://github.com/JuliaPackaging/Yggdrasil/pull/5568

**Comment by mfiano** [comment]
I see. That's quite unfortunate, and above my skill level. Sadly, this has been a deal-breaker for some projects of mine for quite some time.

**Comment by Gnimuc** [comment]
OK. As I seem to be the only maintainer at the moment, I'll give it a look later today. :)

**Comment by mfiano** [comment]
That sounds great. I'll watch both topics for updates. Thanks!

**Comment by Gnimuc** [comment]
@mfiano The master branch is SDL 2.24.2 now. I've no plan to add a new release because this new version is not battle-tested.

**Comment by mfiano** [comment]
I'll do my best to test it out when I get some free time. I'll open a new issue for anything I discover. Thank you very much.

**Pull request merged**
